/**
 * generated by Xtext 2.11.0
 */
package at.uibk.ase.ex3.componentDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Base Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see at.uibk.ase.ex3.componentDsl.ComponentDslPackage#getEntityBaseType()
 * @model
 * @generated
 */
public interface EntityBaseType extends EObject
{
} // EntityBaseType
