/**
 * generated by Xtext 2.11.0
 */
package at.uibk.ase.ex3.componentDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Order</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.uibk.ase.ex3.componentDsl.Order#getSource <em>Source</em>}</li>
 *   <li>{@link at.uibk.ase.ex3.componentDsl.Order#getSourceName <em>Source Name</em>}</li>
 *   <li>{@link at.uibk.ase.ex3.componentDsl.Order#getSourceVersion <em>Source Version</em>}</li>
 * </ul>
 *
 * @see at.uibk.ase.ex3.componentDsl.ComponentDslPackage#getOrder()
 * @model
 * @generated
 */
public interface Order extends Action
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' containment reference.
   * @see #setSource(EntityType)
   * @see at.uibk.ase.ex3.componentDsl.ComponentDslPackage#getOrder_Source()
   * @model containment="true"
   * @generated
   */
  EntityType getSource();

  /**
   * Sets the value of the '{@link at.uibk.ase.ex3.componentDsl.Order#getSource <em>Source</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' containment reference.
   * @see #getSource()
   * @generated
   */
  void setSource(EntityType value);

  /**
   * Returns the value of the '<em><b>Source Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Name</em>' attribute.
   * @see #setSourceName(String)
   * @see at.uibk.ase.ex3.componentDsl.ComponentDslPackage#getOrder_SourceName()
   * @model
   * @generated
   */
  String getSourceName();

  /**
   * Sets the value of the '{@link at.uibk.ase.ex3.componentDsl.Order#getSourceName <em>Source Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Name</em>' attribute.
   * @see #getSourceName()
   * @generated
   */
  void setSourceName(String value);

  /**
   * Returns the value of the '<em><b>Source Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source Version</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Version</em>' attribute.
   * @see #setSourceVersion(String)
   * @see at.uibk.ase.ex3.componentDsl.ComponentDslPackage#getOrder_SourceVersion()
   * @model
   * @generated
   */
  String getSourceVersion();

  /**
   * Sets the value of the '{@link at.uibk.ase.ex3.componentDsl.Order#getSourceVersion <em>Source Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Version</em>' attribute.
   * @see #getSourceVersion()
   * @generated
   */
  void setSourceVersion(String value);

} // Order
