/**
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment3.generator;

import com.google.common.collect.Iterators;
import java.util.Iterator;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class GameGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    TreeIterator<EObject> all = resource.getAllContents();
    Iterator<uibk.dsl.assignment3.game.Object> allObjects = Iterators.<uibk.dsl.assignment3.game.Object>filter(all, uibk.dsl.assignment3.game.Object.class);
    final Function1<uibk.dsl.assignment3.game.Object, String> _function = (uibk.dsl.assignment3.game.Object it) -> {
      return it.getName();
    };
    String greeting = IteratorExtensions.join(IteratorExtensions.<uibk.dsl.assignment3.game.Object, String>map(allObjects, _function), ", ");
    fsa.generateFile("greetings.txt", ("People to greet: " + greeting));
  }
}
