/*
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment1.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractJsonldConverterValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(uibk.dsl.assignment1.jsonldConverter.JsonldConverterPackage.eINSTANCE);
		return result;
	}
	
}
