/**
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment1.ide;

import uibk.dsl.assignment1.ide.AbstractJsonldConverterIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class JsonldConverterIdeModule extends AbstractJsonldConverterIdeModule {
}
