/**
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment1.jsonldConverter.impl;

import org.eclipse.emf.ecore.EClass;

import uibk.dsl.assignment1.jsonldConverter.DataType;
import uibk.dsl.assignment1.jsonldConverter.JsonldConverterPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DataTypeImpl extends TypeImpl implements DataType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DataTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JsonldConverterPackage.Literals.DATA_TYPE;
  }

} //DataTypeImpl
