/*
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment1


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class JsonldConverterRuntimeModule extends AbstractJsonldConverterRuntimeModule {
}
