/*
 * generated by Xtext 2.12.0
 */
package uibk.assignment4.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GroovyRuntimeModule extends AbstractGroovyRuntimeModule {
}
