/*
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment1.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uibk.dsl.assignment1.ui.internal.Assignment1Activator;

public class JsonldConverterUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Assignment1Activator.getInstance().getInjector("uibk.dsl.assignment1.JsonldConverter");
	}

}
