/**
 * generated by Xtext 2.11.0
 */
package at.uibk.ase.ex3.ide;

import at.uibk.ase.ex3.ComponentDslRuntimeModule;
import at.uibk.ase.ex3.ComponentDslStandaloneSetup;
import at.uibk.ase.ex3.ide.ComponentDslIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ComponentDslIdeSetup extends ComponentDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    ComponentDslRuntimeModule _componentDslRuntimeModule = new ComponentDslRuntimeModule();
    ComponentDslIdeModule _componentDslIdeModule = new ComponentDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_componentDslRuntimeModule, _componentDslIdeModule));
  }
}
