/*
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment3.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGameScopeProvider extends DelegatingScopeProvider {
}
