/**
 * generated by Xtext 2.11.0
 */
package at.uibk.ase.ex3.ui.contentassist;

import at.uibk.ase.ex3.ui.contentassist.AbstractComponentDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ComponentDslProposalProvider extends AbstractComponentDslProposalProvider {
}
