/**
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment3.ide;

import uibk.dsl.assignment3.ide.AbstractGameIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GameIdeModule extends AbstractGameIdeModule {
}
