/**
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment3.validation;

import uibk.dsl.assignment3.validation.AbstractGameValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GameValidator extends AbstractGameValidator {
}
