/*
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment3.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import uibk.dsl.assignment3.ide.contentassist.antlr.internal.InternalGameParser;
import uibk.dsl.assignment3.services.GameGrammarAccess;

public class GameParser extends AbstractContentAssistParser {

	@Inject
	private GameGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalGameParser createParser() {
		InternalGameParser result = new InternalGameParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getIngredientAccess().getAlternatives(), "rule__Ingredient__Alternatives");
					put(grammarAccess.getCharacterAccess().getNameAlternatives_1_0(), "rule__Character__NameAlternatives_1_0");
					put(grammarAccess.getObjectAccess().getNameAlternatives_1_0(), "rule__Object__NameAlternatives_1_0");
					put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
					put(grammarAccess.getAdventureAccess().getGroup_0(), "rule__Adventure__Group_0__0");
					put(grammarAccess.getAdventureAccess().getGroup_1(), "rule__Adventure__Group_1__0");
					put(grammarAccess.getSceneAccess().getGroup(), "rule__Scene__Group__0");
					put(grammarAccess.getSceneAccess().getGroup_3(), "rule__Scene__Group_3__0");
					put(grammarAccess.getSceneAccess().getGroup_3_3(), "rule__Scene__Group_3_3__0");
					put(grammarAccess.getSceneAccess().getGroup_6(), "rule__Scene__Group_6__0");
					put(grammarAccess.getSceneAccess().getGroup_6_3(), "rule__Scene__Group_6_3__0");
					put(grammarAccess.getCharacterAccess().getGroup(), "rule__Character__Group__0");
					put(grammarAccess.getCharacterAccess().getGroup_7(), "rule__Character__Group_7__0");
					put(grammarAccess.getCharacterAccess().getGroup_7_3(), "rule__Character__Group_7_3__0");
					put(grammarAccess.getObjectAccess().getGroup(), "rule__Object__Group__0");
					put(grammarAccess.getObjectAccess().getGroup_2(), "rule__Object__Group_2__0");
					put(grammarAccess.getObjectAccess().getGroup_8(), "rule__Object__Group_8__0");
					put(grammarAccess.getObjectAccess().getGroup_8_3(), "rule__Object__Group_8_3__0");
					put(grammarAccess.getStepAccess().getGroup(), "rule__Step__Group__0");
					put(grammarAccess.getStepAccess().getGroup_5(), "rule__Step__Group_5__0");
					put(grammarAccess.getAdventureAccess().getStartSceneAssignment_0_1(), "rule__Adventure__StartSceneAssignment_0_1");
					put(grammarAccess.getAdventureAccess().getEndSceneAssignment_1_1(), "rule__Adventure__EndSceneAssignment_1_1");
					put(grammarAccess.getAdventureAccess().getIngredientsAssignment_2(), "rule__Adventure__IngredientsAssignment_2");
					put(grammarAccess.getSceneAccess().getNameAssignment_1(), "rule__Scene__NameAssignment_1");
					put(grammarAccess.getSceneAccess().getObjectsAssignment_3_2(), "rule__Scene__ObjectsAssignment_3_2");
					put(grammarAccess.getSceneAccess().getObjectsAssignment_3_3_1(), "rule__Scene__ObjectsAssignment_3_3_1");
					put(grammarAccess.getSceneAccess().getDescriptionAssignment_5(), "rule__Scene__DescriptionAssignment_5");
					put(grammarAccess.getSceneAccess().getActionsAssignment_6_2(), "rule__Scene__ActionsAssignment_6_2");
					put(grammarAccess.getSceneAccess().getActionsAssignment_6_3_1(), "rule__Scene__ActionsAssignment_6_3_1");
					put(grammarAccess.getCharacterAccess().getNameAssignment_1(), "rule__Character__NameAssignment_1");
					put(grammarAccess.getCharacterAccess().getDescriptionAssignment_4(), "rule__Character__DescriptionAssignment_4");
					put(grammarAccess.getCharacterAccess().getHealthPointsAssignment_6(), "rule__Character__HealthPointsAssignment_6");
					put(grammarAccess.getCharacterAccess().getActionsAssignment_7_2(), "rule__Character__ActionsAssignment_7_2");
					put(grammarAccess.getCharacterAccess().getActionsAssignment_7_3_1(), "rule__Character__ActionsAssignment_7_3_1");
					put(grammarAccess.getObjectAccess().getNameAssignment_1(), "rule__Object__NameAssignment_1");
					put(grammarAccess.getObjectAccess().getSuperTypeAssignment_2_2(), "rule__Object__SuperTypeAssignment_2_2");
					put(grammarAccess.getObjectAccess().getDescriptionAssignment_5(), "rule__Object__DescriptionAssignment_5");
					put(grammarAccess.getObjectAccess().getHealthPointsAssignment_7(), "rule__Object__HealthPointsAssignment_7");
					put(grammarAccess.getObjectAccess().getActionsAssignment_8_2(), "rule__Object__ActionsAssignment_8_2");
					put(grammarAccess.getObjectAccess().getActionsAssignment_8_3_1(), "rule__Object__ActionsAssignment_8_3_1");
					put(grammarAccess.getStepAccess().getActionAssignment_2(), "rule__Step__ActionAssignment_2");
					put(grammarAccess.getStepAccess().getTargetObjectAssignment_3(), "rule__Step__TargetObjectAssignment_3");
					put(grammarAccess.getStepAccess().getValidAssignment_5_1(), "rule__Step__ValidAssignment_5_1");
					put(grammarAccess.getStepAccess().getSceneAssignment_7(), "rule__Step__SceneAssignment_7");
					put(grammarAccess.getAdventureAccess().getUnorderedGroup(), "rule__Adventure__UnorderedGroup");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GameGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GameGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
