/**
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment3.game;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Adventure</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uibk.dsl.assignment3.game.Adventure#getStartScene <em>Start Scene</em>}</li>
 *   <li>{@link uibk.dsl.assignment3.game.Adventure#getEndScene <em>End Scene</em>}</li>
 *   <li>{@link uibk.dsl.assignment3.game.Adventure#getIngredients <em>Ingredients</em>}</li>
 * </ul>
 *
 * @see uibk.dsl.assignment3.game.GamePackage#getAdventure()
 * @model
 * @generated
 */
public interface Adventure extends EObject
{
  /**
   * Returns the value of the '<em><b>Start Scene</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Start Scene</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Scene</em>' reference.
   * @see #setStartScene(Scene)
   * @see uibk.dsl.assignment3.game.GamePackage#getAdventure_StartScene()
   * @model
   * @generated
   */
  Scene getStartScene();

  /**
   * Sets the value of the '{@link uibk.dsl.assignment3.game.Adventure#getStartScene <em>Start Scene</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Scene</em>' reference.
   * @see #getStartScene()
   * @generated
   */
  void setStartScene(Scene value);

  /**
   * Returns the value of the '<em><b>End Scene</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>End Scene</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Scene</em>' reference.
   * @see #setEndScene(Scene)
   * @see uibk.dsl.assignment3.game.GamePackage#getAdventure_EndScene()
   * @model
   * @generated
   */
  Scene getEndScene();

  /**
   * Sets the value of the '{@link uibk.dsl.assignment3.game.Adventure#getEndScene <em>End Scene</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End Scene</em>' reference.
   * @see #getEndScene()
   * @generated
   */
  void setEndScene(Scene value);

  /**
   * Returns the value of the '<em><b>Ingredients</b></em>' containment reference list.
   * The list contents are of type {@link uibk.dsl.assignment3.game.Ingredient}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ingredients</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ingredients</em>' containment reference list.
   * @see uibk.dsl.assignment3.game.GamePackage#getAdventure_Ingredients()
   * @model containment="true"
   * @generated
   */
  EList<Ingredient> getIngredients();

} // Adventure
