/**
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment3.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hero</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uibk.dsl.assignment3.game.Hero#getHealthPoints <em>Health Points</em>}</li>
 * </ul>
 *
 * @see uibk.dsl.assignment3.game.GamePackage#getHero()
 * @model
 * @generated
 */
public interface Hero extends Ingredient
{
  /**
   * Returns the value of the '<em><b>Health Points</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Health Points</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Health Points</em>' attribute.
   * @see #setHealthPoints(String)
   * @see uibk.dsl.assignment3.game.GamePackage#getHero_HealthPoints()
   * @model
   * @generated
   */
  String getHealthPoints();

  /**
   * Sets the value of the '{@link uibk.dsl.assignment3.game.Hero#getHealthPoints <em>Health Points</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Health Points</em>' attribute.
   * @see #getHealthPoints()
   * @generated
   */
  void setHealthPoints(String value);

} // Hero
