/**
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment3.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uibk.dsl.assignment3.game.GamePackage#getObject()
 * @model
 * @generated
 */
public interface Object extends Ingredient
{
} // Object
