/**
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment3.game;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scene</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uibk.dsl.assignment3.game.Scene#getObjects <em>Objects</em>}</li>
 *   <li>{@link uibk.dsl.assignment3.game.Scene#getDescription <em>Description</em>}</li>
 *   <li>{@link uibk.dsl.assignment3.game.Scene#getActions <em>Actions</em>}</li>
 * </ul>
 *
 * @see uibk.dsl.assignment3.game.GamePackage#getScene()
 * @model
 * @generated
 */
public interface Scene extends Ingredient
{
  /**
   * Returns the value of the '<em><b>Objects</b></em>' reference list.
   * The list contents are of type {@link uibk.dsl.assignment3.game.Object}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Objects</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objects</em>' reference list.
   * @see uibk.dsl.assignment3.game.GamePackage#getScene_Objects()
   * @model
   * @generated
   */
  EList<uibk.dsl.assignment3.game.Object> getObjects();

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see uibk.dsl.assignment3.game.GamePackage#getScene_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link uibk.dsl.assignment3.game.Scene#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link uibk.dsl.assignment3.game.Step}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see uibk.dsl.assignment3.game.GamePackage#getScene_Actions()
   * @model containment="true"
   * @generated
   */
  EList<Step> getActions();

} // Scene
