/**
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment3;

import uibk.dsl.assignment3.GameStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GameStandaloneSetup extends GameStandaloneSetupGenerated {
  public static void doSetup() {
    new GameStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
