/**
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment1.ui.contentassist;

import uibk.dsl.assignment1.ui.contentassist.AbstractJsonldConverterProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class JsonldConverterProposalProvider extends AbstractJsonldConverterProposalProvider {
}
