/**
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment3.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uibk.dsl.assignment3.game.Step#getAction <em>Action</em>}</li>
 *   <li>{@link uibk.dsl.assignment3.game.Step#getTargetObject <em>Target Object</em>}</li>
 *   <li>{@link uibk.dsl.assignment3.game.Step#getValid <em>Valid</em>}</li>
 *   <li>{@link uibk.dsl.assignment3.game.Step#getScene <em>Scene</em>}</li>
 * </ul>
 *
 * @see uibk.dsl.assignment3.game.GamePackage#getStep()
 * @model
 * @generated
 */
public interface Step extends EObject
{
  /**
   * Returns the value of the '<em><b>Action</b></em>' attribute.
   * The literals are from the enumeration {@link uibk.dsl.assignment3.game.Action}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' attribute.
   * @see uibk.dsl.assignment3.game.Action
   * @see #setAction(Action)
   * @see uibk.dsl.assignment3.game.GamePackage#getStep_Action()
   * @model
   * @generated
   */
  Action getAction();

  /**
   * Sets the value of the '{@link uibk.dsl.assignment3.game.Step#getAction <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' attribute.
   * @see uibk.dsl.assignment3.game.Action
   * @see #getAction()
   * @generated
   */
  void setAction(Action value);

  /**
   * Returns the value of the '<em><b>Target Object</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target Object</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Object</em>' reference.
   * @see #setTargetObject(uibk.dsl.assignment3.game.Object)
   * @see uibk.dsl.assignment3.game.GamePackage#getStep_TargetObject()
   * @model
   * @generated
   */
  uibk.dsl.assignment3.game.Object getTargetObject();

  /**
   * Sets the value of the '{@link uibk.dsl.assignment3.game.Step#getTargetObject <em>Target Object</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Object</em>' reference.
   * @see #getTargetObject()
   * @generated
   */
  void setTargetObject(uibk.dsl.assignment3.game.Object value);

  /**
   * Returns the value of the '<em><b>Valid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Valid</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valid</em>' attribute.
   * @see #setValid(String)
   * @see uibk.dsl.assignment3.game.GamePackage#getStep_Valid()
   * @model
   * @generated
   */
  String getValid();

  /**
   * Sets the value of the '{@link uibk.dsl.assignment3.game.Step#getValid <em>Valid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valid</em>' attribute.
   * @see #getValid()
   * @generated
   */
  void setValid(String value);

  /**
   * Returns the value of the '<em><b>Scene</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Scene</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scene</em>' reference.
   * @see #setScene(Scene)
   * @see uibk.dsl.assignment3.game.GamePackage#getStep_Scene()
   * @model
   * @generated
   */
  Scene getScene();

  /**
   * Sets the value of the '{@link uibk.dsl.assignment3.game.Step#getScene <em>Scene</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scene</em>' reference.
   * @see #getScene()
   * @generated
   */
  void setScene(Scene value);

} // Step
