/*
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment3.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import uibk.dsl.assignment3.mario.ui.internal.MarioActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GameExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MarioActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MarioActivator.getInstance().getInjector(MarioActivator.UIBK_DSL_ASSIGNMENT3_GAME);
	}
	
}
