/**
 * generated by Xtext 2.11.0
 */
package at.uibk.ase.ex3.componentDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see at.uibk.ase.ex3.componentDsl.ComponentDslPackage#getCreate()
 * @model
 * @generated
 */
public interface Create extends Action
{
} // Create
