/**
 * generated by Xtext 2.11.0
 */
package at.uibk.ase.ex3.componentDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.uibk.ase.ex3.componentDsl.Entity#getName <em>Name</em>}</li>
 *   <li>{@link at.uibk.ase.ex3.componentDsl.Entity#getParent <em>Parent</em>}</li>
 *   <li>{@link at.uibk.ase.ex3.componentDsl.Entity#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see at.uibk.ase.ex3.componentDsl.ComponentDslPackage#getEntity()
 * @model
 * @generated
 */
public interface Entity extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see at.uibk.ase.ex3.componentDsl.ComponentDslPackage#getEntity_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link at.uibk.ase.ex3.componentDsl.Entity#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parent</b></em>' attribute.
   * The literals are from the enumeration {@link at.uibk.ase.ex3.componentDsl.EntityBaseTypeEnum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parent</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parent</em>' attribute.
   * @see at.uibk.ase.ex3.componentDsl.EntityBaseTypeEnum
   * @see #setParent(EntityBaseTypeEnum)
   * @see at.uibk.ase.ex3.componentDsl.ComponentDslPackage#getEntity_Parent()
   * @model
   * @generated
   */
  EntityBaseTypeEnum getParent();

  /**
   * Sets the value of the '{@link at.uibk.ase.ex3.componentDsl.Entity#getParent <em>Parent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parent</em>' attribute.
   * @see at.uibk.ase.ex3.componentDsl.EntityBaseTypeEnum
   * @see #getParent()
   * @generated
   */
  void setParent(EntityBaseTypeEnum value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link at.uibk.ase.ex3.componentDsl.Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attributes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see at.uibk.ase.ex3.componentDsl.ComponentDslPackage#getEntity_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

} // Entity
