/**
 * generated by Xtext 2.11.0
 */
package org.xtext.asea3.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create Project</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.asea3.mydsl.myDsl.MyDslPackage#getCreateProject()
 * @model
 * @generated
 */
public interface CreateProject extends Type
{
} // CreateProject
