/**
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment1.jsonldConverter;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uibk.dsl.assignment1.jsonldConverter.JsonldConverterPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
