/**
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment1.jsonldConverter;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uibk.dsl.assignment1.jsonldConverter.Enum#getFeatures <em>Features</em>}</li>
 * </ul>
 *
 * @see uibk.dsl.assignment1.jsonldConverter.JsonldConverterPackage#getEnum()
 * @model
 * @generated
 */
public interface Enum extends Type
{
  /**
   * Returns the value of the '<em><b>Features</b></em>' containment reference list.
   * The list contents are of type {@link uibk.dsl.assignment1.jsonldConverter.EnumItem}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Features</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Features</em>' containment reference list.
   * @see uibk.dsl.assignment1.jsonldConverter.JsonldConverterPackage#getEnum_Features()
   * @model containment="true"
   * @generated
   */
  EList<EnumItem> getFeatures();

} // Enum
