/*
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment3.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import uibk.dsl.assignment3.game.Adventure;
import uibk.dsl.assignment3.game.GamePackage;
import uibk.dsl.assignment3.game.Scene;
import uibk.dsl.assignment3.game.Step;
import uibk.dsl.assignment3.services.GameGrammarAccess;

@SuppressWarnings("all")
public class GameSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private GameGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == GamePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case GamePackage.ADVENTURE:
				sequence_Adventure(context, (Adventure) semanticObject); 
				return; 
			case GamePackage.OBJECT:
				sequence_Object(context, (uibk.dsl.assignment3.game.Object) semanticObject); 
				return; 
			case GamePackage.SCENE:
				sequence_Scene(context, (Scene) semanticObject); 
				return; 
			case GamePackage.STEP:
				sequence_Step(context, (Step) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Adventure returns Adventure
	 *
	 * Constraint:
	 *     (startScene=[Scene|ID] | endScene=[Scene|ID] | ingredients+=Ingredient)+
	 */
	protected void sequence_Adventure(ISerializationContext context, Adventure semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Ingredient returns Object
	 *     Object returns Object
	 *
	 * Constraint:
	 *     ((name=STRING | name=ID) description=STRING)
	 */
	protected void sequence_Object(ISerializationContext context, uibk.dsl.assignment3.game.Object semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Ingredient returns Scene
	 *     Scene returns Scene
	 *
	 * Constraint:
	 *     (name=ID (objects+=[Object|ID] objects+=[Object|ID]*)? description=STRING (actions+=Step actions+=Step*)?)
	 */
	protected void sequence_Scene(ISerializationContext context, Scene semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Step returns Step
	 *
	 * Constraint:
	 *     (action=Action targetObject=[Object|ID] (preposition=Preposition otherObject=[Object|ID])? (valid=STRING | default=STRING)+ scene=[Scene|ID])
	 */
	protected void sequence_Step(ISerializationContext context, Step semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
