/**
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment1.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import uibk.dsl.assignment1.ui.AbstractJsonldConverterUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class JsonldConverterUiModule extends AbstractJsonldConverterUiModule {
  public JsonldConverterUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
