/*
 * generated by Xtext 2.12.0
 */
package uibk.dsl.assignment1.ide


/**
 * Use this class to register ide components.
 */
class JsonldConverterIdeModule extends AbstractJsonldConverterIdeModule {
}
