/**
 * generated by Xtext 2.11.0
 */
package at.uibk.ase.ex3.ui;

import at.uibk.ase.ex3.ui.AbstractComponentDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ComponentDslUiModule extends AbstractComponentDslUiModule {
  public ComponentDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
